### PR TITLE
Update publish-pypi.yml

### PR DESCRIPTION
**Pull request by catchthemonster**
- os: ubuntu-latest 
     python: 312 
     platform_id: manylinux_x86_64 
     manylinux_image: manylinux2014 

added twice for 32 and x64 linux debian variants
--sasha

### CODE REVIEW

**Comment by bluesheeptoken** [comment]
Hello Sasha, thanks for the PR !
It looks like the CI underneath starts to support python 3.12 since version 2.13: https://github.com/pypa/cibuildwheel/releases/tag/v2.13.0

I will update your PR if you don't mind, thanks for the help !

**Review by bluesheeptoken — APPROVED** [review]

**Comment by bluesheeptoken** [comment]
I will try to do a release tonight, thanks for bootstrapping the work !

**Comment by catchthemonster** [comment]
NO problem Felix can I try to load that version?

**Comment by bluesheeptoken** [comment]
1.3.4 has just been published, you can now install it with Python 3.12 !

**Pull request merged**
